// <auto-generated />
namespace Peregrine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Add_External_auth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_External_auth));
        
        string IMigrationMetadata.Id
        {
            get { return "201503221731520_Add_External_auth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
